# Use the official .NET 6.0 SDK image from Microsoft
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Copy the project file and restore dependencies
COPY *.csproj ./
RUN dotnet restore

# Copy the rest of the project files and build the project
COPY . ./
RUN dotnet publish -c Release -o out

# Use the official .NET 6.0 runtime image from Microsoft
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out .

# Expose the port your application is running on
EXPOSE 5000

# Set the entry point to run your application
ENTRYPOINT ["dotnet", "Website.dll"]
